export const mockData = [
  {
    id: 1,
    title: "DevOps Engineer",
    company: "Wiraa",
    location: "United States",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Associate",
    postedAt: "2h ago",
  },
  {
    id: 2,
    title: "Senior Food Scientist",
    company: "normine lombard",
    location: "United States",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Mid-Senior level",
    postedAt: "2h ago",
  },
  {
    id: 3,
    title: "Salesforce DevOps Engineer",
    company: "optimal",
    location: "India",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Entry level",
    postedAt: "2h ago",
  },
  {
    id: 4,
    title: "Machine Learning Engineer Intern",
    company: "gemmo ai",
    location: "Italy",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Part-time",
    experience: "Internship",
    postedAt: "3h ago",
  },
  {
    id: 5,
    title: "Recruitment Coordinator",
    company: "behavioral health link",
    location: "United States",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Entry level",
    postedAt: "2h ago",
  },
  {
    id: 6,
    title: "Founding AI Engineer",
    company: "Arena",
    location: "United States",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Entry level",
    postedAt: "6h ago",
  },
  {
    id: 7,
    title: "Product Manager",
    company: "BrainRocket",
    location: "Spain",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Mid-Senior level",
    postedAt: "3h ago",
  },
  {
    id: 8,
    title: "Cyber Security Engineer",
    company: "cloudbig technology",
    location: "San Francisco Bay Area",
    tags: ["Visa Sponsorship", "Relocation", "Remote"],
    type: "Full-time",
    experience: "Entry level",
    postedAt: "7h ago",
  }
];
